CREATE TABLE users_enriched (
    id INT NOT NULL PRIMARY KEY,
    age INT,
    gender VARCHAR(255),
    country VARCHAR(255),
    city VARCHAR(255),
    traffic_source VARCHAR(255),
    n_orders INT,
    n_order_items INT,
    revenue FLOAT,
    purchased_categories VARCHAR(255)[],
    created_at TIMESTAMP,
    first_purchase_date TIMESTAMP,
    last_purchase_date TIMESTAMP,
    active_days INT,
    inactive_days INT,
    avg_days_to_order INT,
    items_per_order INT,
    avg_order_value FLOAT,
    segment VARCHAR(255),
    churn_flag VARCHAR(255)
)